### ISSUE TITLE
ios Bulid Fali

### ISSUE THREAD

**Issue by 7chenys** [wukongyang/react-native-svga-play#1]

**Comment by 7chenys** [comment]
Declaration of 'OSAtomicCompareAndSwapPtrBarrier' must be imported from module 'Darwin.libkern.OSAtomic' before it is required

**Comment by 7chenys** [comment]
我刚看到了解决方法，我想请问下如果是不添加进xcode的话，代码的具体位置我需要添加在哪

**Comment by wukongyang** [comment]
https://github.com/wukongyang/SVGAPlayer-rn#possible-issues

**Comment by wukongyang** [comment]
> Declaration of 'OSAtomicCompareAndSwapPtrBarrier' must be imported from module 'Darwin.libkern.OSAtomic' before it is required

https://github.com/wukongyang/SVGAPlayer-rn#possible-issues
