### ISSUE TITLE
iOS中，动画显示的偏大

### ISSUE THREAD

**Issue by 7chenys** [wukongyang/react-native-svga-play#2]
在iOS中，动画显示的偏大，偏的很多，但是容器的宽高是正常的

**Comment by 7chenys** [comment]
有什么方法可以控制一下吗，比如resizeMode

**Comment by wukongyang** [comment]
没有复现你的问题，示例动画就是在ios上运行的效果https://github.com/wukongyang/SVGAPlayer-rn/blob/master/daka.gif
